import {Category} from "../types";

export const TOKEN_LIST = [
    { token:'CARREFOUR', category: Category.FOOD},
    { token:'MARKET BUCURESTI', category: Category.FOOD},
    { token:'OZKARDES', category: Category.FOOD},
    { token:'TRANSAMIR', category: Category.FOOD},
    { token:'MEGA IMAGE', category: Category.FOOD},
    { token:'IMBISS', category: Category.FOOD},
    { token:'Glovo', category: Category.FOOD},
    { token:'CARNIVALE', category: Category.FOOD},
    { token:'Foodpanda', category: Category.FOOD},
    { token:'TAKSIM', category: Category.FOOD},
    { token:'PROFI', category: Category.FOOD},
    { token:'CORA', category: Category.FOOD},
    { token:'KEBAP', category: Category.FOOD},
    { token:'FOOD', category: Category.FOOD},
    { token:'CHEF', category: Category.FOOD},
    { token:'KFC', category: Category.FOOD},
    { token:'CARTOF', category: Category.FOOD},
    { token:'MEGAIMAGE', category: Category.FOOD},
    { token:'RESTAURANT', category: Category.FOOD},
    { token:'STARBUCKS', category: Category.FOOD},
    { token:'Auchan', category: Category.FOOD},
    { token:'DABO', category: Category.FOOD},
    { token:'DELICATES', category: Category.FOOD},
    { token:'FORNETTI', category: Category.FOOD},
    { token:'DONER', category: Category.FOOD},
    { token:'BERARILOR', category: Category.FOOD},
    { token:'CAFE', category: Category.FOOD},
    { token:'CATERING', category: Category.FOOD},
    { token:'TACO BELL', category: Category.FOOD},
    { token:'MADO', category: Category.FOOD},
    { token:'MESOPOTAMIA', category: Category.FOOD},
    { token:'pizza', category: Category.FOOD},
    { token:'SOUP', category: Category.FOOD},
    { token:'SUBWAY', category: Category.FOOD},
    { token:'PEP&PEPPER', category: Category.FOOD},
    { token:'CIORBARIE', category: Category.FOOD},
    { token:'BEST MARKET', category: Category.FOOD},
    { token:'MOO GELATO', category: Category.FOOD},
    { token:'PRANZO', category: Category.FOOD},
    { token:'COLUMBUS', category: Category.FOOD},
    { token:'CC COTROCENI', category: Category.FOOD},
    { token:'CREMERIA', category: Category.FOOD},
    { token:'CHOPSTIX', category: Category.FOOD},
    { token:'BISTRO', category: Category.FOOD},
    { token:'KAUFLAND', category: Category.FOOD},
    { token:'LAGARDERE TRAVEL', category: Category.FOOD},
    { token:'PROD COM MARCO', category: Category.FOOD},
    { token:'CUPTORUL CU LEMNE2', category: Category.FOOD},
    { token:'GUSTO', category: Category.FOOD},
    { token:'PIZZICATO', category: Category.FOOD},
    { token:'DINNER PLAZA', category: Category.FOOD},
    { token:'HUB TIMP NOI VAST', category: Category.FOOD},
    { token:'Crist Nom Star SRL', category: Category.FOOD},
    { token:'1608006 SBX Plaza Ro', category: Category.FOOD},
    { token:'1608034 SBX PLOIESTI', category: Category.FOOD},
    { token:'COZONACI', category: Category.FOOD},
    { token:'KEBAB', category: Category.FOOD},
    { token:'TUCANO', category: Category.FOOD},
    { token:'TAZZ', category: Category.FOOD},
    { token:'IRISH PUB', category: Category.FOOD},
    { token:'Gyros', category: Category.FOOD},
    { token:'Thessalonikis', category: Category.FOOD},
    { token:'ANA PAN', category: Category.FOOD},
    { token:'STRONGMNDCORP', category: Category.FOOD},
    { token:'Miky Progres SRL Popesti', category: Category.FOOD},
    { token:'SC SET CORPORATION', category: Category.FOOD},
    { token:'IMPEX ', category: Category.FOOD},
    { token:'SC SET CORPORATION SRL', category: Category.FOOD},
    { token:'HENG YUAN', category: Category.FOOD},


    { token:'ATM', category: Category.CASH_WITHDRAW},
    { token:'ING OFFICE', category: Category.CASH_WITHDRAW},
    { token:'BRD BUCURESTI', category: Category.CASH_WITHDRAW},
    { token:'Dan Horia Constantin', category: Category.CASH_WITHDRAW},


    { token:'13 Septembrie Bucuresti', category: Category.CASH_WITHDRAW},
    { token:'BNA PROMENADA', category: Category.CASH_WITHDRAW},
    { token:'UBER', category: Category.TRANSPORT},
    { token:'ROMPETROL', category: Category.TRANSPORT},
    { token:'LIM', category: Category.TRANSPORT},
    { token:'REGIOCALATORI', category: Category.TRANSPORT},
    { token:'CFRCALATO', category: Category.TRANSPORT},
    { token:'METROREX', category: Category.TRANSPORT},
    { token:'OMV', category: Category.TRANSPORT},
    { token:'GARA DE NORD', category: Category.TRANSPORT},
    { token:'STB SA BUCURESTI', category: Category.TRANSPORT},
    { token:'CFR', category: Category.TRANSPORT},

    { token:'ZARA', category: Category.SHOPPING},
    { token:'PULL & BEAR', category: Category.SHOPPING},
    { token:'C & A', category: Category.SHOPPING},
    { token:'Deichmann', category: Category.SHOPPING},
    { token:'BOR RETAIL SA BUCURESTI', category: Category.SHOPPING},
    { token:'SUVARI', category: Category.SHOPPING},
    { token:'BERSHKA', category: Category.SHOPPING},
    { token:'SPORTISIMO', category: Category.SHOPPING},
    { token:'HUMANIC', category: Category.SHOPPING},
    { token:'NEW YORKER', category: Category.SHOPPING},
    { token:'CCC', category: Category.SHOPPING},
    { token:'KOTON', category: Category.SHOPPING},
    { token:'PEPCO', category: Category.SHOPPING},
    { token:'H&M', category: Category.SHOPPING},
    { token:'TINERVIS', category: Category.SHOPPING},
    { token:'CROPP', category: Category.SHOPPING},
    { token:'PANDORA', category: Category.SHOPPING},
    { token:'DS DAMAT', category: Category.SHOPPING},
    { token:'ALTEX PLAZA', category: Category.SHOPPING},
    { token:'NCR06508 BUCURESTI', category: Category.SHOPPING},
    { token:'BTRA REPREZENTANTA CITY', category: Category.SHOPPING},
    { token:'GRADINARU CRISTINA PFA', category: Category.SHOPPING},
    { token:'COLINS', category: Category.SHOPPING},

    { token:'RO66 JD BUC', category: Category.SHOPPING},
    { token:'EMAG.RO', category: Category.SHOPPING},
    { token:'ENGIE', category: Category.ENERGY},
    { token:'ENEL', category: Category.ENERGY},
    { token:'RCS', category: Category.ENERGY},
    { token:'TRADE', category: Category.INVESTMENT},
    { token:'Binance', category: Category.INVESTMENT},
    { token:'eToro', category: Category.INVESTMENT},
    { token:'transak.com', category: Category.INVESTMENT},
    { token:'JetBrains', category: Category.INVESTMENT},
    { token:'DirectDebit ARC ROMANIA', category: Category.CHARITY},
    { token:'SENSIBLU', category: Category.PHARMA},
    { token:'HELP NET', category: Category.PHARMA},
    { token:'SANADOR', category: Category.PHARMA},
    { token:'MEDICAL AP', category: Category.PHARMA},
    { token:'DENTAL PRAXIS', category: Category.PHARMA},
    { token:'CLINICA 32', category: Category.PHARMA},
    { token:'SSB PLAZA ROMANIA', category: Category.PHARMA},
    { token:'salariu', category: Category.SALARY},
    { token:'STEAMGAMES', category: Category.GAMING},
    { token:'PC GARAGE', category: Category.GAMING},
    { token:'STEAMPOWERED', category: Category.GAMING},
    { token:'EPIC GAMES', category: Category.GAMING},
    { token:'ORIGIN.COM', category: Category.GAMING},
    { token:'mojang', category: Category.GAMING},
    { token:'FORTNITE', category: Category.GAMING},
    { token:'STEAM PURCHASE SEATTLE', category: Category.GAMING},
    { token:'Ramp Swaps London', category: Category.GAMING},

    { token:'CINEMA CITY', category: Category.ENTERTAINMENT},
    { token:'DARETOPAINT', category: Category.ENTERTAINMENT},
    { token:'cinemacity.ro', category: Category.ENTERTAINMENT},
    { token:'PET PRODUCT', category: Category.ENTERTAINMENT},
    { token:'gotinder', category: Category.ENTERTAINMENT},
    { token:'SC LICENTEONLINE SRL BEIUS', category: Category.ENTERTAINMENT},
    { token:'TEATRUL DE COMEDIE', category: Category.ENTERTAINMENT},
    { token:'DIVERTA', category: Category.ENTERTAINMENT},

    { token:'OPIB/1', category: Category.RENT},
    { token:'Revolut', category: Category.REVOLUT},
    { token:'COMISION ADMINISTRARE PACHET', category: Category.BANKING},
    { token:'OPH/10658/42025183 ', category: Category.SALARY},
    { token:'YouTubePremium', category: Category.SUBSCRIPTIONS},
    { token:'NETFLIX.COM', category: Category.SUBSCRIPTIONS},
    { token:'INTERBELIC', category: Category.CLUBBING},
    { token:'Guesthouse', category: Category.CLUBBING},
    { token:'CLUB', category: Category.CLUBBING},
    { token:'EXPIRAT', category: Category.CLUBBING},
    { token:'STEREO DRINKS', category: Category.CLUBBING},

    { token:'BIKALDI', category: Category.CLUBBING},
    { token:'WEALTH COFFEESHOP', category: Category.CLUBBING},
    { token:'SO COFFEE', category: Category.CLUBBING},
    { token:'MERON', category: Category.CLUBBING},
]
