import {Category} from "./types";
export const TOKEN_LIST = [
    { token:'CARREFOUR', category: Category.FOOD},
    { token:'MARKET BUCURESTI', category: Category.FOOD},
    { token:'OZKARDES', category: Category.FOOD},
    { token:'TRANSAMIR', category: Category.FOOD},
    { token:'MEGA IMAGE', category: Category.FOOD},
    { token:'IMBISS', category: Category.FOOD},
    { token:'Glovo', category: Category.FOOD},
    { token:'CARNIVALE', category: Category.FOOD},
    { token:'Foodpanda', category: Category.FOOD},
    { token:'TAKSIM', category: Category.FOOD},
    { token:'PROFI', category: Category.FOOD},
    { token:'CORA', category: Category.FOOD},
    { token:'KEBAP', category: Category.FOOD},
    { token:'FOOD', category: Category.FOOD},
    { token:'CHEF', category: Category.FOOD},
    { token:'KFC', category: Category.FOOD},
    { token:'CARTOF', category: Category.FOOD},
    { token:'MEGAIMAGE', category: Category.FOOD},
    { token:'RESTAURANT', category: Category.FOOD},
    { token:'STARBUCKS', category: Category.FOOD},
    { token:'Auchan', category: Category.FOOD},
    { token:'DABO', category: Category.FOOD},
    { token:'DELICATES', category: Category.FOOD},
    { token:'FORNETTI', category: Category.FOOD},
    { token:'DONER', category: Category.FOOD},
    { token:'BERARILOR', category: Category.FOOD},
    { token:'CAFE', category: Category.FOOD},
    { token:'CATERING', category: Category.FOOD},
    { token:'TACO BELL', category: Category.FOOD},
    { token:'MADO', category: Category.FOOD},
    { token:'MESOPOTAMIA', category: Category.FOOD},
    { token:'pizza', category: Category.FOOD},
    { token:'SOUP', category: Category.FOOD},
    { token:'SUBWAY', category: Category.FOOD},
    { token:'PEP&PEPPER', category: Category.FOOD},
    { token:'CIORBARIE', category: Category.FOOD},
    { token:'BEST MARKET', category: Category.FOOD},
    { token:'MOO GELATO', category: Category.FOOD},
    { token:'PRANZO', category: Category.FOOD},
    { token:'COLUMBUS', category: Category.FOOD},
    { token:'CC COTROCENI', category: Category.FOOD},
    { token:'CREMERIA', category: Category.FOOD},
    { token:'CHOPSTIX', category: Category.FOOD},
    { token:'BISTRO', category: Category.FOOD},
    { token:'KAUFLAND', category: Category.FOOD},
    { token:'LAGARDERE TRAVEL', category: Category.FOOD},
    { token:'PROD COM MARCO', category: Category.FOOD},
    { token:'CUPTORUL CU LEMNE2', category: Category.FOOD},
    { token:'GUSTO', category: Category.FOOD},
    { token:'PIZZICATO', category: Category.FOOD},
    { token:'ATM', category: Category.CASH_WITHDRAW},
    { token:'ING OFFICE', category: Category.CASH_WITHDRAW},
    { token:'BRD BUCURESTI', category: Category.CASH_WITHDRAW},
    { token:'13 Septembrie Bucuresti', category: Category.CASH_WITHDRAW},
    { token:'BNA PROMENADA', category: Category.CASH_WITHDRAW},
    { token:'UBER', category: Category.TRANSPORT},
    { token:'ROMPETROL', category: Category.TRANSPORT},
    { token:'LIM', category: Category.TRANSPORT},
    { token:'REGIOCALATORI', category: Category.TRANSPORT},
    { token:'ZARA', category: Category.SHOPING},
    { token:'PULL & BEAR', category: Category.SHOPING},
    { token:'C & A', category: Category.SHOPING},
    { token:'Deichmann', category: Category.SHOPING},
    { token:'SUVARI', category: Category.SHOPING},
    { token:'BERSHKA', category: Category.SHOPING},
    { token:'SPORTISIMO', category: Category.SHOPING},
    { token:'HUMANIC', category: Category.SHOPING},
    { token:'NEW YORKER', category: Category.SHOPING},
    { token:'CCC', category: Category.SHOPING},
    { token:'KOTON', category: Category.SHOPING},
    { token:'H&M', category: Category.SHOPING},
    { token:'TINERVIS', category: Category.SHOPING},
    { token:'CROPP', category: Category.SHOPING},
    { token:'PANDORA', category: Category.SHOPING},
    { token:'ENGIE', category: Category.ENERGY},
    { token:'ENEL', category: Category.ENERGY},
    { token:'RCS', category: Category.ENERGY},
    { token:'TRADE', category: Category.INVESTMENT},
    { token:'Binance', category: Category.INVESTMENT},
    { token:'DirectDebit ARC ROMANIA', category: Category.CHARITY},
    { token:'SENSIBLU', category: Category.PHARMA},
    { token:'HELP NET', category: Category.PHARMA},
    { token:'SANADOR', category: Category.PHARMA},
    { token:'MEDICAL AP', category: Category.PHARMA},
    { token:'DENTAL PRAXIS', category: Category.PHARMA},
    { token:'CLINICA 32', category: Category.PHARMA},
    { token:'salariu', category: Category.SALARY},
    { token:'STEAMGAMES', category: Category.GAMING},
    { token:'PC GARAGE', category: Category.GAMING},
    { token:'STEAMPOWERED', category: Category.GAMING},
    { token:'EPIC GAMES', category: Category.GAMING},
    { token:'ORIGIN.COM', category: Category.GAMING},
    { token:'mojang', category: Category.GAMING},
    { token:'FORTNITE', category: Category.GAMING},
]
